# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f038dc1ad543812379994f803bcd19ef4fcffec570bc8551b9b2f433d5bae6550560dc2eac8f99d181c9f59d275ffe24564b5fe29b069dec26137bfc96ac23

test:
  secret_key_base: 8c6b526e37bcfc21a13a4b4396a851d9fd3a4bc903560873e60d914f12afa65ac573a27c03db958672a65fa5ef287882aaae52b61224348dd5afe9cdd310edee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
